### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Jeric-X** [Jeric-X/SyncClipboard#36]
- [x] 使用代理服务器
- [x] 加密，端到端 or 自签名Https
- [ ] 服务端多用户 https://github.com/Jeric-X/SyncClipboard/issues/45
- [x] 剪贴板历史记录
- [x] 文件类型黑白名单
- [x] 快捷键：复制并上传/下载并粘贴 https://github.com/Jeric-X/SyncClipboard/issues/55
- [x] 全局快捷键 https://github.com/Jeric-X/SyncClipboard/issues/34

**Comment by howie6879** [comment]
非常不错的项目，已经推荐到[老胡的周刊](https://weekly.howie6879.com/2024/05-13~05-19.%E8%80%81%E8%83%A1%E7%9A%84%E5%91%A8%E5%88%8A%EF%BC%88%E7%AC%AC142%E6%9C%9F%EF%BC%89.html)

请问是否考虑有个 web 页面（服务端），或者客户端有个 tab 查看历史所有的同步内容 方便浏览历史，毕竟查看历史复制内容都已经是个需求了，也有很多 app，多设备历史剪切汇总听起来就很不错

**Comment by howie6879** [comment]
> 多设备历史剪切汇总

确实是这个产品独有且有必要的，因为用这个软件就是多设备这个大前提哈哈

**Comment by Zdowson** [comment]
> @howie6879
> 
> 感谢推荐
> 
> 目前在Windows、Mac上已经有很多十分优秀的剪贴板历史记录APP，Windows甚至自带了历史记录功能，我确实没什么动力来做这件事，但是剪贴板同步工具有一个历史记录的功能也非常的顺理成章，包括`多设备历史剪切汇总`听着确实不错，比较纠结，我会把这个功能加到List中，在更多用户提出需求或者自己下定决心时填坑

非常需要

**Comment by feranwq** [comment]
提几个希望实现的功能, 
1. 客户端自动更新---设备比较多, 都更新一遍还挺麻烦的
2. 服务端配置支持从环境变量读取---一般要改的只有账密,可以优先考虑只做常用配置支持变量
3. 新增两个动作, 忽略文件大小限制进行上传下载---偶尔有个大文件同步不需要再去调整配置

**Comment by Jeric-X** [comment]
> 提几个希望实现的功能,
> 
> 1. 客户端自动更新---设备比较多, 都更新一遍还挺麻烦的
> 2. 服务端配置支持从环境变量读取---一般要改的只有账密,可以优先考虑只做常用配置支持变量
> 3. 新增两个动作, 忽略文件大小限制进行上传下载---偶尔有个大文件同步不需要再去调整配置
@feranwq 

可以每个单独提issue，比较有动力，现在新增功能大都是从issue列表里排的

**Comment by ferocknew** [comment]
历史记录列表，并不需要系统的历史记录，而是服务端获取到数据的历史记录。

这点，其实数据结构上应该已经是现成的，例如，日志。。。

所以，只需要有个api 可以获取到，然后客户端，可以列出，并选择以后，重新复制到当前剪贴板，就行了。

**Comment by foxdodo** [comment]
> 历史记录列表，并不需要系统的历史记录，而是服务端获取到数据的历史记录。
> 
> 这点，其实数据结构上应该已经是现成的，例如，日志。。。
> 
> 所以，只需要有个api 可以获取到，然后客户端，可以列出，并选择以后，重新复制到当前剪贴板，就行了。

那么有没有人愿意写个pr呢😁

**Comment by Jeric-X** [comment]
这个issue很久没用过了，不再使用
